/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.ds.multiproject;

public class App {
    public static void main(String[] args) {
        System.out.println(GreetingHelper.sayHello(args));
    }
}
