/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.ds.multiproject;

public class GreetingHelper {

    public static String sayHello(String... args) {
        if (args.length == 0) {
            throw new IllegalArgumentException("No one to greet");
        }
        return "Hello " + String.join(", ", args) + "!";
    }
}
