/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.ds.multiproject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestGreetingHelper {
    @Test void testGreet() {
        assertEquals("Hello Giovanni, Andrea!", GreetingHelper.sayHello("Giovanni", "Andrea"));
    }
}
